# Aufgabenstellung {#sec-Aufgaben}

Versuchen Sie zunächst selbst eine Lösung zu finden bevor Sie sich die Auflösungen anschauen. Hierbei kann das freie Nachschlagewerk von @grSchlR hilfreich sein.

```{r}
#| label: AufgabenHidden
#| include: false
library(stats)
library(tidyverse)
```

## Häufigkeitsverteilungen {#sec-aufgabeHaeufig}

### Aufgabe [-@sec-A01] Kinder in Familien {#sec-A01}
::: {.callout-note appearance="simple" icon=false}
Für 25 Familien liegt die Anzahl an Kindern vor:

> 1, 2, 4, 2, 2, 2, 3, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 3, 1, 2, 2, 1, 2

a) Erstellen Sie ein Datenframe mit der Variable `Kinder` und übertragen Sie die Daten.
b) Erzeugen Sie eine einfache Häufigkeitstabelle
c) Erzeugen Sie ein Balkendiagramm der Häufigkeiten
d) Erzeugen Sie eine vollständige Häufigkeitstabelle, inklusive absoluter, relativer und jeweils kumulativer Häufigkeiten

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L01
:::

\smallskip\ 


### Aufgabe [-@sec-A02] Patienten in der Notaufnahme {#sec-A02}
::: {.callout-note appearance="simple" icon=false}
Den gesamten November über wurde die Anzahl an Patienten in der Notaufnahme erhoben

\begin{center}
15 \quad 23 \quad 12 \quad 10 \quad 28 \quad 50 \quad 12 \quad 17 \quad 20 \quad 21 \quad 18 \quad 13 \quad 11 \quad 12 \quad 26 \\
30 \quad 6 \quad 16 \quad 19 \quad 22 \quad 14 \quad 17 \quad 21 \quad 28 \quad 9 \quad 16 \quad 13 \quad 11 \quad 16 \quad 20
\end{center}

a) Erstellen Sie ein Datenframe mit der Variable `Patienten` und übertragen Sie die Daten.
b) Erzeugen Sie ein Boxplot. Gibt es Ausreißer? Wenn ja, entfernen Sie diese, bevor Sie weitermachen.
c) Erzeugen Sie eine Häufigkeitstabelle, welche die Daten in 5 Klassen gruppiert.
d) Erzeugen Sie ein Histogram der klassierten absoluten Häufigkeiten.
e) Erzeugen Sie ebenso Histogramme der relativen und jeweils kumulativen Häufigkeiten, inklusive Polygonzügen.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L02
:::
\smallskip\ 



### Aufgabe [-@sec-A03] Blutgruppen {#sec-A03}
::: {.callout-note appearance="simple" icon=false}
Von 30 Personen wurden die Blutgruppen wie folgt bestimmt:

\begin{center}
A, B, B, A, AB, 0, 0, A, B, B, A, A, A, A, AB,\\
A, A, A, B, 0, B, B, B, A, A, A, 0, A, AB, 0. 
\end{center}

a) Erstellen Sie ein Datenframe mit der Variable `Blutgruppe` und übertragen Sie die Daten.
b) Erzeugen Sie eine Häufigkeitstabelle
c) Erzeugen Sie ein Kreisdiagramm
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L03
:::
\smallskip\ 





### Aufgabe [-@sec-A04] Familienstand {#sec-A04}
::: {.callout-note appearance="simple" icon=false}
Das Alter und der Familienstand von 28 Personen wurden wie folgt erhoben:


| Familienstand | Alter |   |   |   |   |   |   |   |   |  
|---------------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Single        | 31 | 45 |  35 | 65 | 21 | 38 | 62 | 22 | 31 |
| Verheiratet   | 72 | 39 | 62 | 59 | 25 | 44 | 54 |
| Verwitwet     | 80 | 68 | 65 | 40 | 78 | 69 | 75 |
| Geschieden    | 31 | 65 | 59 | 58 | 50 |


a) Erstellen Sie ein Datenframe mit den Variablen `Alter` und `Familienstand` und übertragen Sie die Daten.
b) Erzeugen Sie für jeden `Familienstand` eine Häufigkeitstabelle des `Alters`.
c) Erzeugen Sie für jeden `Familienstand` eine Boxplot des `Alters`. Gibt es Ausreißer? In welcher Gruppe streut das Alter am meisten?
d) Erzeugen Sie für jeden `Familienstand` eine Histogram des `Alters`. Wie unterscheiden sich die Histogramme?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L04
:::
\smallskip\ 





### Aufgabe [-@sec-A05] Handballverletzungen {#sec-A05}
::: {.callout-note appearance="simple" icon=false}
Die Anzahl der Verletzungen von Handballspielern eines Teams wurden wie folgt erhoben:

> 0, 1, 2, 1, 3, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 3, 2, 1, 2, 1, 0, 1



a) Erstellen Sie eine Häufigkeitstabelle
b) Erzeugen Sie ein Säulendiagramm der relativen und kumulativen relativen Häufigkeiten.
c) Erzeugen Sie ein Boxplot
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L05
:::
\smallskip\ 




### Aufgabe [-@sec-A06] Körpergröße {#sec-A06}
::: {.callout-note appearance="simple" icon=false}
Von 30 Studierenden wurde die Körpergröße gemessen

> 179, 173, 181, 170, 158, 174, 172, 166, 194, 185,\newline 162, 187, 198, 177, 178, 165, 154, 188, 166, 171,\newline 175, 182, 167, 169, 172, 186, 172, 176, 168, 187



a) Erstellen Sie ein Histogram der Körpergröße mit Klassen von 150cm bis 200cm, die jeweils 10cm breit sind. 
b) Gibt es Ausreißer?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L06
:::
\smallskip\ 

### Aufgabe [-@sec-A07] Neugeborene {#sec-A07}
::: {.callout-note appearance="simple" icon=false}
Der Datensatz `neonates` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/neonates.RData>] enthält Informationen über eine Stichprobe von 320 Neugeborenen, die im Laufe eines Jahres nach normaler Schwangerschaftsdauer geboren wurden.

a) Erstellen Sie die Häufigkeitstabelle des APGAR-Scores nach 1 Minute. Wenn ein Score von 3 oder weniger anzeigt, dass das Neugeborene in einem kritischen Zusatand ist, wie viel Prozent der Neugeborenen in der Stichprobe sind dann in einem kritischen Zustand?

b) Erstellen Sie die Häufigkeitstabelle des Geburtsgewichts der Neugeborenen, indem Sie die Daten in Klassen mit einer Breite von 0,5 kg von 2 bis 4,5 kg einteilen. Welches Intervall enthält die meisten Neugeborenen?

c) Vergleichen Sie die Häufigkeitsverteilung des APGAR-Scores nach 1 Minute für Mütter unter 20 Jahren und für Mütter über 20 Jahren. Welche Gruppe hat mehr Neugeborene in kritischem Zustand?

d) Vergleichen Sie die relative Häufigkeitsverteilung des Geburtsgewichts der Neugeborenen, je nachdem, ob die Mutter während der Schwangerschaft geraucht hat oder nicht. Wenn ein Gewicht unter 2,5 kg als niedriges Gewicht gilt, welche Gruppe hat einen höheren Prozentsatz an Neugeborenen mit niedrigem Gewicht?

e) Berechnen Sie die Prävalenz von Neugeborenen mit niedrigem Gewicht für Mütter, die vor der Schwangerschaft geraucht haben, und den Nichtraucherinnen.

f) Berechnen Sie das relative Risiko eines niedrigen Geburtsgewichts des Neugeborenen, wenn die Mutter während der Schwangerschaft raucht, im Vergleich dazu, wenn die Mutter nicht raucht.

g) Erstellen Sie ein Balkendiagramm des APGAR-Scores nach 1 Minute. Welcher Score ist am häufigsten?

h) Erstellen Sie das Balkendiagramm der kumulierten relativen Häufigkeit des APGAR-Scores nach 1 Minute. Unter welchem Wert liegen die Hälfte der Neugeborenen?

i) Vergleichen Sie die Balkendiagramme der relativen Häufigkeitsverteilungen des APGAR-Scores nach 1 Minute, je nachdem, ob die Mutter während der Schwangerschaft geraucht hat oder nicht. Welche Schlussfolgerungen können gezogen werden?

j) Erstellen Sie ein Histogramm der Geburtsgewichte der Neugeborenen mit Klassenbreiten von 0,5 kg von 2 bis 4,5 kg. Welche Klasse enthält die meisten Neugeborenen?

k) Vergleichen Sie die relativen Häufigkeitshistogramme der Geburtsgewichte der Neugeborenen, mit Klassenbreiten von 0,5 kg von 2 bis 4,5 kg, je nachdem, ob die Mutter während der Schwangerschaft geraucht hat oder nicht. Welche Gruppe hat Neugeborene mit geringeren Gewichten?

l) Vergleichen Sie die relativen Häufigkeitshistogramme der Geburtsgewichte der Neugeborenen, mit Klassenbreiten von 0,5 kg von 2 bis 4,5 kg, je nachdem, ob die Mutter vor der Schwangerschaft geraucht hat oder nicht. Welche Schlussfolgerungen können gezogen werden?

m) Erstellen Sie ein Boxplot der Geburtsgewichte der Neugeborenen. Welcher Gewichtsbereich kann in der Stichprobe als normal angesehen werden? Gibt es Ausreißer in der Stichprobe?

n) Vergleichen Sie die Boxplots der Geburtsgewichte der Neugeborenen je nachdem, ob die Mutter während der Schwangerschaft geraucht hat oder nicht und ob die Mutter unter 20 oder über 20 Jahre alt war. Welche Gruppe hat eine größere zentrale Streuung? Welche Gruppe hat Neugeborene mit geringerem Gewicht?

o) Vergleichen Sie die Boxplots der APGAR-Scores nach 1 Minute und nach 5 Minuten. Welche Variable hat eine größere zentrale Streuung?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-L07
:::

\newpage





## Stichprobenstatistik {#sec-aufgabeStichprobe}

Bei diesen Aufgaben geht es vor allem um Lage- und Streuungskenngrößen.


### Aufgabe [-@sec-B01] Kinder in Familien {#sec-B01}
::: {.callout-note appearance="simple" icon=false}
Die Anzahl an Kindern in einer Stichprobe aus 25 Familien sind:

> 1, 2, 4, 2, 2, 2, 3, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 3, 1, 2, 2, 1, 2

a) Erstellen Sie ein Datenframe mit der Variable `Kinder` und übertragen Sie die Daten.
b) Berechnen Sie das arithmetische Mittel, die Varianz sowie die Standardabweichung für die Anzahl an Kindern.
c) Berechnen Sie die Quartile, die Spannweite, den Interquartilsabstand, das dritte Dezil sowie das 68te Perzentil.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB01
:::
\smallskip\ 



### Aufgabe [-@sec-B02] Patienten in Notaufnahme {#sec-B02}
::: {.callout-note appearance="simple" icon=false}
Den gesamten November über wurde die Anzahl an Patienten in der Notaufnahme erhoben

\begin{center}
15 \quad 23 \quad 12 \quad 10 \quad 28 \quad 50 \quad 12 \quad 17 \quad 20 \quad 21 \quad 18 \quad 13 \quad 11 \quad 12 \quad 26 \\
30 \quad 6 \quad 16 \quad 19 \quad 22 \quad 14 \quad 17 \quad 21 \quad 28 \quad 9 \quad 16 \quad 13 \quad 11 \quad 16 \quad 20
\end{center}

a) Erstellen Sie ein Datenframe mit der Variable `Patienten` und übertragen Sie die Daten.
b) Berechnen Sie das arithmetische Mittel, die Varianz, die Standardabweichung und den Variationskoeffizienten.
c) Berechnen Sie die Skewness (Schiefe) und Kurtosis ("Spitzigkeit") und interpretieren Sie die Werte.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB02
:::
\smallskip\ 



### Aufgabe [-@sec-B03] Studierendenbewertung {#sec-B03}
::: {.callout-note appearance="simple" icon=false}
Im letzten R-Kurs haben 20 Studierende folgende Abschlussbewertungen erhalten

> SS, AP, SS, AP, AP, NT, NT, AP, SB, SS \newline SB, SS, AP, AP, NT, AP, SS, NT, SS, NT

a) Erstellen Sie ein Datenframe mit der Variable `Bewertung` und übertragen Sie die Daten.
b) Wandeln Sie die `Bewertung` in Punkte um, nach dem Schema 
   "`SS`" = 2,5 | "`AP`" = 6 | "`NT`" = 8 | "`SB`" = 9,5.
c) Bestimmen Sie den Median und den Interquartilsabstand.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB03
:::
\smallskip\ 



### Aufgabe [-@sec-B04] Körpergröße nach Geschlecht {#sec-B04}
::: {.callout-note appearance="simple" icon=false}
Von 30 Studierenden wurde die Körpergröße wie folgt gemessen:


| Geschlecht | Größe |
|---|---------------|
| weiblich   | 173, 158, 174, 166, 162, 177, 165, 154, 166, 182, 169, 172, 170, 168 |
| männlich   | 179, 181, 172, 194, 185, 187, 198, 178, 188, 171, 175, 167, 186, 172, 176, 187 |

a) Erstellen Sie ein Datenframe mit den Variable `Geschlecht` und `Koerpergroesse` und übertragen Sie die Daten.
b) Bestimmen Sie in Abhängigkeit zum `Geschlecht` das arithmetische Mittel, den Median, die Varianz, die Standardabweichung sowie die Quartile.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB04
:::

\smallskip\ 



### Aufgabe [-@sec-B05] Handballverletzungen {#sec-B05}
::: {.callout-note appearance="simple" icon=false}
Die Anzahl der Verletzungen von Handballspielern eines Teams wurden wie folgt erhoben:

> 0, 1, 2, 1, 3, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 3, 2, 1, 2, 1, 0, 1

a) Bestimmen Sie das arithmetische Mittel, den Median, die Varianz sowie die Standardabweichung der Verletzungen.
b) Bestimmen Sie die Skewness und Kortosis der Verteilung.
c) Berechnen Sie das vierte und achte Dezil der Verteilung.   
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB05
:::
\smallskip\ 



### Aufgabe [-@sec-B06] Blutdruckmessung {#sec-B06}
::: {.callout-note appearance="simple" icon=false}
Wir möchten die Zuverlässigkeit zweier Blutdruckmonitore bestimmen. Gerät 1 misst den Blutdruck am Handgelenk, Gerät 2 am Unterarm. Es wurden 8 Messungen mit jedem Gerät bei der selben Person durchgeführt, wobei folgende systolischen Werte gemessen wurden:

| Position   | Messdaten |
|------------|-----------|
| Unterarm   | 111, 109, 112, 111, 113, 113, 114, 111 |
| Handgelenk | 115, 113, 117, 116, 112, 112, 117, 112 |

Welcher Monitor funktioniert besser?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB06
:::

\smallskip\ 



### Aufgabe [-@sec-B07] Alter und Familienstand {#sec-B07}
::: {.callout-note appearance="simple" icon=false}
Das Alter und der Familienstand von 28 Personen wurden wie folgt erhoben:


| Familienstand | Alter |   |   |   |   |   |   |   |   |  
|---------------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Single        | 31 | 45 |  35 | 65 | 21 | 38 | 62 | 22 | 31 |
| Verheiratet   | 72 | 39 | 62 | 59 | 25 | 44 | 54 |
| Verwitwet     | 80 | 68 | 65 | 40 | 78 | 69 | 75 |
| Geschieden    | 31 | 65 | 59 | 58 | 50 |


a) Bestimmen Sie das arithmetische Mittel, den Median, die Varianz sowie die Standardabweichung des `Alters` für jeden `Familienstand`.
b) Welche Gruppe hat den "besten" Mittelwert?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB07
:::
\smallskip\ 




### Aufgabe [-@sec-B08] Tabak, Alkohol und Blutdruck {#sec-B08}
::: {.callout-note appearance="simple" icon=false}
Eine Studie möchte den möglichen Zusammenhang zwischen dem Blutdruck und dem Alkohol- und Tabakkonsum untersuchen. Hierzu wurden folgende Daten von 25 Personen erhoben.


\begin{center}
\begin{tabular}{lccccccccccccc}
\hline
Rauchen  & ja & nein & ja & ja & ja & nein & nein & ja & nein & ja & nein & ja & nein \\
Alkohol & nein & nein & ja & ja & nein & nein & ja & ja & nein & ja & nein & ja & ja \\
Blutdruck & 80 & 92 & 75 & 56 & 89 & 93 & 101 & 67 & 89 & 63 & 98 & 58 & 91 \\
\hline
\\
\hline
Rauchen  & ja & nein & nein & ja & nein & nein & nein & ja & nein & ja & nein & ja \\
Alkohol & ja & nein & ja & ja & nein & nein & ja & ja & ja & nein & ja & nein \\
Blutdruck & 71 & 52 & 98 & 104 & 57 & 89 & 70 & 93 & 69 & 82 & 70 & 49 \\
\hline
\end{tabular}
\end{center}

a) Vergleichen Sie das arithmetische Mittel, die Standardabweichung, die Skewness und Kurtosis des `Blutdrucks` zwischen Rauchern und Nichtrauchern.
b) Vergleichen Sie die selben Werte zwischen der Alkohol- und Nicht-Alkoholgruppe.
c) Vergleichen Sie die selben Werte zwischen der Raucher- und Alkoholgruppe, zwischen der Raucher- und Nicht-Alkoholgruppe, der Nichtraucher- und Alkoholgruppe sowie der Nichtraucher- und Nicht-Alkoholgruppe.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LB07
:::
\bigskip\ 


## Lineare Regression {#sec-aufgabeLinReg}

### Aufgabe [-@sec-C01] X und Y {#sec-C01}
::: {.callout-note appearance="simple" icon=false}
Bei 10 Personen wurden `x` und `y` erhoben.


| x | 0 |  1 |  2 |  3 |4 | 5 | 6 | 7 | 8 | 9  |  
|---|---|---|---|---|---|---|---|---|---|---|
| y |  2 | 5 |8 |11 | 14 | 17 | 20 | 23 |  26 | 29 |


a) Erstellen Sie ein Datenframe mit den Variablen `x` und `y`.
b) Erzeugen Sie ein Scatterplot von  `x` und `y`. Bestimmen Sie anhand des Plots, welche Regressionsfunktion die Daten am besten erklären würde.
c) Führen Sie die Regression durch.
d) Fügen Sie die Regressionsfunktion `y erklärt durch x`  dem Plot hinzu.
e) Fügen Sie die Regressionsfunktion `x erklärt durch y` ebenfalls dem Plot hinzu, aber in roter Farbe.
f) Wie groß sind die Residuen?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC01
:::
\smallskip\ 



### Aufgabe [-@sec-C02] Lernen und Durchfallen {#sec-C02}
::: {.callout-note appearance="simple" icon=false}
Eine Studie gibt vor, den Zusammenhang zwischen den täglichen Lernstunden und der Anzahl nicht bestandener
Prüfungen im Semester zu untersuchen. Bei 30 Studierenden wurden folgende Werte erhoben:

$$
\begin{array}{cccccccc}
\text{Lernzeit} & \text{durchgefallen} &  & \text{Lernzeit} & \text{durchgefallen} & & \text{Lernzeit} &
\text{durchgefallen}
\\
\cline{1-2}\cline{4-5}\cline{7-8}
3.5 & 1 & & 2.2 & 2 & & 1.3 & 4 \\
0.6 & 5 & & 3.3 & 0 & & 3.1 & 0 \\
2.8 & 1 & & 1.7 & 3 & & 2.3 & 2 \\
2.5 & 3 & & 1.1 & 3 & & 3.2 & 2 \\
2.6 & 1 & & 2.0 & 3 & & 0.9 & 4 \\
3.9 & 0 & & 3.5 & 0 & & 1.7 & 2 \\
1.5 & 3 & & 2.1 & 2 & & 0.2 & 5 \\
0.7 & 3 & & 1.8 & 2 & & 2.9 & 1 \\
3.6 & 1 & & 1.1 & 4 & & 1.0 & 3 \\
3.7 & 1 & & 0.7 & 4 & & 2.3 & 2 \\
\end{array}
$$



a) Erstellen Sie ein Datenframe mit den Variablen `Lernen` und `Durchgefallen`.
b) Erzeugen Sie eine Kreuztabelle der Variablen `Lernen` und `Durchgefallen`.
c) Führen Sie eine lineare Regression `Durchgefallen erklärt durch Lernen` durch und plotten Sie Ihr Ergebnis.
d) Wie lauten die Regressionskoeffizient des Modells, und wie ist er zu interpretieren?
e) Ist das soeben erstellte Modell *besser* als das in @sec-C01 berechnete? Vergleichen Sie zur Beantwortung die Residuen beider Modelle.
f) Berechnen Sie den linearen Bestimmungskoeffizient und den Korrelationskoeffizient. Ist das lineare Modell ein gutes Modell, um die Beziehung zwischen den gescheiterten Prüfungen und den täglichen Studienzeiten zu erklären? Wie viel Prozent der Variabilität der durchgefallenen Prüfungen wird durch das lineare Modell erklärt?
g) Benutzen Sie das lineare Modell, um die Anzahl an durchgefallenen Prüfungen für einen Studierenden zu bestimmen, der 3 Stunden Lernzeit investiert hat. Wie glaubwürdig ist die Vorhersage?
h) Wie viele Stunden Lernzeit wird benötigt, um alle Kurse zu bestehen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC02
:::
\smallskip\ 



### Aufgabe [-@sec-C03] Metabolismus {#sec-C03}
::: {.callout-note appearance="simple" icon=false}
Um herauszufinden, wie der Körper Alkohol verstoffwechselt, hat ein Proband einen Liter Wein zügig getrunken. Anschließend wurde alle 30 Minuten der Blutalkoholspiegel gemessen.

|Minuten| 30 |60| 90| 120|150| 180 |210|
|---|---|---|---|---|---|---|---|
|Alkohol (g/l) | 1.6 | 1.7| 1.5| 1.1| 0.7| 0.2| 2.1|


a) Erstellen Sie ein Datenframe mit den Variablen `Minuten` und `Alkohol`.
b) Bestimmen Sie den passenden Korrelationskoeffizienten. Werden die Daten ausreichend gut durch das Modell beschrieben?
c) Plotten Sie das lineare Regressionsmodell `Alkohol erklärt durch Minuten`. Gibt es Punkte mit großen Residuen? Wenn ja, entfernen Sie diese und führen die Berechnungen erneut durch. Hat sich der Korrelationskoeffizient verbessert?
d) Mit welcher Geschwindigkeit wird der Alkohol pro Minute verstoffwechselt?
e) Wenn es gesetzlich erlaubt wäre, mit einem Blutalkoholwert von $0,3$ g/l Auto zu fahren, wie lange muss die Person warten, nachdem sie $1$ Liter Weingetrunken hat, um wieder fahrtüchtig zu sein? Wie zuverlässig ist diese Vorhersage?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC03
:::
\smallskip\ 



### Aufgabe [-@sec-C04] Alter und Körpergröße {#sec-C04}
::: {.callout-note appearance="simple" icon=false}
Im Datensatz `age.height` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/age.height.RData>] sind Alter und Körpergröße von 30 Probanden enthalten.


a) Laden Sie den Datensatz `age.height` in Ihre R-Session.
b) Berechnen Sie die Regressionsgerade `Größe erklärt durch Alter`. Ist das lineare Modell geeignet, den Zusammenhang zwischen `Alter` und `Körpergröße` zu erklären?
c) Erstellen Sie eine Punktwolke inklusive der Regressionsgeraden. Ab welchem Alter ändert sich die Punktetendenz?
d) Erstellen Sie eine Gruppierungsvariable, welche `Alter` in einen ordinalen Faktor mit den Ausprägungen "`jünger als 20`" und "`20 und älter`" einteilt.
e) Führen Sie die lineare Regressionsanalyse für beide Gruppen erneut durch. In welcher Gruppe wird der Zusammenhang zwischen `Alter` und `Körpergröße` am besten erklärt?
f) Plotten Sie die Modelle.
g) Welche Körpergröße sagt Ihr Modell für eine 14jährige Person vorher, und welche für eine 38jährige Person?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC04
:::
\smallskip\ 


### Aufgabe [-@sec-C05] Wirksamkeitsverlust {#sec-C05}
::: {.callout-note appearance="simple" icon=false}
Eine Studie Untersucht den Wirksamkeitsverlust eines Medikaments, das über Jahre von vielen Probanden eingenommen wurde.
Folgende Aussagen zur Wirksamkeit konnten aus den Daten ermittelt werden.

| Jahr | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|
| Wirksamkeit (\%) | 96 | 84 | 70 | 58 | 52 |


a) Führen Sie eine lineare Regression `Wirksamkeit erklärt durch Jahr` durch und plotten Sie Ihr Ergebnis.
b) Wie große ist der jährliche Wirksamkeitsverlust in \%?
c) Nach wie vielen Jahren ist die Wirksamkeit bei 80%, und nach wie vielen bei 0%? Sind beide Werte gleich zuverlässig?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC05
:::
\smallskip\ 


### Aufgabe [-@sec-C06] Dosierung {#sec-C06}
::: {.callout-note appearance="simple" icon=false}
In einer Studie über die Wirkung verschiedener Dosen eines Medikaments erhielten 2 Patienten 2 mg und benötigten 5 Tage zur Heilung, 4 Patienten erhielten 2 mg und benötigten 6 Tage zur Heilung, 2 Patienten erhielten 3 mg und benötigten 3 Tage zur Heilung, 4 Patienten erhielten 3 mg und benötigten 5 Tage zur Heilung, 1 Patient erhielt 3 mg und benötigte 6 Tage zur Heilung, 5 Patienten erhielten 4 mg und benötigten 3 Tage zur Heilung und 2 Patienten erhielten 4 mg und benötigten 5 Tage zur Heilung. 


a) Berechnen Sie die Regressionsgerade der Heilungstage in Abhängigkeit von der Dosis.
b) Berechnen Sie den Regressionskoeffizienten der Heilungstage in Abhängigkeit von der Dosis und interpretieren Sie ihn.
c) Berechnen Sie den Korrelationskoeffizienten und interpretieren Sie ihn.
d) Bestimmen Sie die erwartete Zeit, die für die Heilung mit einer Dosis von 5 mg benötigt wird. Ist diese Vorhersage zuverlässig? Begründen Sie die Antwort.
e) Welche Dosis muss angewendet werden, um in 4 Tagen zu heilen? Ist diese Vorhersage zuverlässig? Begründen Sie die Antwort.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC06
:::
\smallskip\ 



### Aufgabe [-@sec-C07] Gewicht und Körpergröße {#sec-C07}
::: {.callout-note appearance="simple" icon=false}
Im Datensatz `heigths.weights.students` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/heights.weights.students.RData>] sind Gewicht und Körpergröße von 100 Probanden enthalten.


a) Laden Sie den Datensatz `heigths.weights.students` in Ihre R-Session.
b) Führen Sie eine lineare Regression `Gewicht erklärt durch Größe` durch.
c) Erstellen Sie eine Punktwolke inklusive Regressionsgeraden jeweils für Männer und Frauen getrennt.
d) Berechnen Sie die Bestimmtheitskoeffizienten (R^2^) für beide Modelle. Welches Modell erklärt besser die Beziehung zwischen Gewicht und Größe, das der Männer oder das der Frauen? Begründen Sie die Antwort.
e) Was ist das zu erwartende Gewicht für einen Mann mit 170cm Körpergröße? Und für eine Frau der selben Größe?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC07
:::
\smallskip\ 



### Aufgabe [-@sec-C08] Neugeborene {#sec-C08}
::: {.callout-note appearance="simple" icon=false}
Der Datensatz `neonates` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/neonates.RData>] enthält Informationen über eine Stichprobe von 320 Neugeborenen, die im Laufe eines Jahres nach normaler Schwangerschaftsdauer geboren wurden.

a) Erstellen Sie eine Kreuztabelle vom APGAR-Wert nach 1 Minute und dem Rauchverhalten der Mütter während der Schwangerschaft. Welche Schlüsse lassen sich ziehen?
b) Erstellen Sie eine Kreuztabelle vom APGAR-Wert nach 1 Minute und der Alterskategorie der Mütter. Welche Schlüsse lassen sich ziehen?
c) Führen Sie eine lineare Regression für `Geburtsgewicht erklärt durch Anzahl täglich gerauchter Zigaretten` durch. Gibt es einen starken linearen Zusammenhang?
d) Plotten Sie Ihre Regression. Passt die Regressionsgerade gut zur Punktwolke?
e) Wiederholen Sie die Regression, aber nutzen Sie dieses Mal nur Daten von Raucherinnen. Ist dieses Modell besser oder schlechter als das vorherige? Wieviel Gewicht verliert ein Neugeborenes nach diesem Modell pro täglich gerauchter Zigarette?
f) Welches Geburtsgewicht sagt dieses Modell für ein Neugeborenes vorher, dessen Mutter 5 Zigaretten täglich während der Schwangerschaft geraucht hat? Wieviel für eine Mutter, die 30 Zigaretten täglich raucht. Wie zuverlässich sind diese Ergebnisse?
g) Ändert sich der lineare Zusammenhang, wenn die Daten nach Altersgruppen getrennt untersucht werden?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LC08
:::

\newpage


## Nicht-lineare Regression {#sec-aufgabeNonLinReg}


### Aufgabe [-@sec-D01] Bakterien {#sec-D01}
::: {.callout-note appearance="simple" icon=false}

Die Anzahl an Bakterien in einer Kultur vermehrt sich wie folgt:

| Stunden | 1 | 2|3|4|5|6|7|8|9|
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Bakterien |  25| 28| 47| 65| 86| 121| 190| 290| 362|


a) Erstellen Sie ein Datenframe mit den Variablen `Stunden` und `Bakterien`.
b) Erzeugen Sie ein Scatterplot. Welche Regression würden Sie auf Grundlage des Plots vorschlagen?
c) Berechnen Sie die quadratischen und exponentiellen Modelle für die Bakterienvermehrung über die Zeit.
d) Plotten Sie das bessere Modell in die Punktwolke.
e) Wie viele Bakterien werden nach dem besten Modell 3 Stunden nach Anlegen der Kultur vorhanden sein? Und nach 10 Stunden? Sind diese Vorhersagen zuverlässig?
f) Machen Sie eine möglichst zuverlässige Vorhersage über die Zeit, die benötigt wird, um 100 Bakterien in der Kultur zu haben.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LD01
:::


### Aufgabe [-@sec-D02] Diät {#sec-D02}
::: {.callout-note appearance="simple" icon=false}

Der Datensatz `diet` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/diet.RData>] enthält Informationen über eine Diätenuntersuchung. Für jede Person wurde die Anzahl der Diättage, der Gewichtsverlust und die regelmäßige körperliche Betätigung gemessen.

a) Laden Sie den Datensatz `diet` in Ihre R-Session.
b) Erstellen Sie eine Punktwolke. Welche Art von Modell erklärt auf Grundlage der Punktwolke den Gewichtsverlust pro Diättag besser?
c) Berechnen Sie das Regressionsmodell, welches den Gewichtsverlust mit der Anzahl an Diättagen am besten (im Vergleich zu anderen) erklären kann. Wird das Modell zuverlässige Vorhersagen machen?
d) Plotten Sie Ihr Modell.
e) Berechnen Sie das Regressionsmodell, das den Gewichtsverlust mit den
Tagen der Diät für die Gruppe der Personen, die sich nicht regelmäßig körperlich betätigen, am besten erklären kann.
f) Wiederholen Sie die Analyse für die Gruppe, die sich regelmäßig körperlich betätigt.
g) Benutzen Sie die erstellen Modelle, um den Gewichtsverlust nach 30 und nach 100 Tagen Diät für Personen, die sich körperlich betätigen, und für solche, die dies nicht tun, vorherzusagen. Sind diese Vorhersagen zuverlässig?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LD02
:::
\smallskip\ 

### Aufgabe [-@sec-D03] Blutkonzentration {#sec-D03}
::: {.callout-note appearance="simple" icon=false}

Die Konzentration eines Arzneimittels im Blut in mg/dl hängt von der Zeit ab, wie aus den folgenden Daten hervorgeht.

| Stunden | 2|3|4|5|6|7|8|
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Konzentration | 25| 36| 48| 64| 86| 114| 168|

a) Benutzen Sie ein exponentielles Modell, um die Konzentration nach 10 Stunden vorherzusagen. Ist die Vorhersage zuverlässig?
b) Benutzen Sie ein logarithmisches Modell um zu bestimmen, nach wie vielen Stunden eine Konzentration von 100 mg/dl erreicht sein wird.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LD03
:::
\smallskip\ 






## Wahrscheinlichkeiten {#sec-aufgabeWahrscheinlich}

### Aufgabe [-@sec-E01] Glücksspiel {#sec-E01}
::: {.callout-note appearance="simple" icon=false}

Lassen Sie in R ...

a) eine beliebige Poker-Spielkarte^[Den Datensatz für ein Pokerkartenspiel erhalten Sie unter <https://www.produnis.de/R/data/cards.RData>] ziehen.
b) 2 Münzen werfen.
c) 2 Würfeln werfen.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE01
:::
\smallskip\ 

### Aufgabe [-@sec-E02] Münzwürfe {#sec-E02}
::: {.callout-note appearance="simple" icon=false}

Wiederholen Sie die Zufallsexperimente und lassen Sie R $10$ mal, $100$ mal $1.000$ mal und $1.000.000$ mal zwei Münzen werfen.

a) Erstellen Sie je eine relative Häufigkeitstabelle der Ergebnisse. Wie sind die Tabellen zu bewerten?
b) Welche theoretischen Wahrscheinlichkeiten haben die möglichen Wurfergebnisse? Stimmen diese mit den beobachteten Ergebnissen überein?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE02
:::
\smallskip\ 



### Aufgabe [-@sec-E03] Medizinschrank {#sec-E03}
::: {.callout-note appearance="simple" icon=false}

In einem Medizinschrank befinden sich drei Boxen mit Medikament A, zwei Boxen mit Medikament B und eine Box mit Medikament C.

a) Ziehen Sie zufällig 3 Boxen, ohne zurücklegen.
b) Ziehen Sie zufällig 3 Boxen, diesmal mit zurücklegen.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE03
:::
\smallskip\ 

### Aufgabe [-@sec-E04] Kinderkrankheiten {#sec-E04}
::: {.callout-note appearance="simple" icon=false}

Eine epidemiologische Untersuchung wurde durchgeführt, um die Lebenszeitprävalenz von drei häufigen Kinderkrankheiten zu ermitteln: Windpocken, Masern und Röteln. Die beobachteten Häufigkeiten sind in der nachstehenden Tabelle aufgeführt.

| Windpocken | Masern | Röteln | Häufigkeit |
|:---:|:---:|:---:|---:|
| No | No| No| 2654|
|No| No| Yes| 1436|
|No| Yes| No| 1682|
|No| Yes| Yes| 668|
|Yes| No| No| 1747|
|Yes| No| Yes| 476|
|Yes| Yes| No| 876|
|Yes| Yes| Yes| 265|

a) Erstellen Sie ein Datenframe mit den Variablen `Windpocken`, `Masern`, `Röteln` und `Häufigkeit` und übertragen Sie die Daten.
b) Erstellen Sie den Wahrscheinlichkeitsraum der Lebenszeitprävalenz.
c) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig gezogene Person Windpocken hatte?
d) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig gezogene Person Windpocken oder Masern hatte?
e) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig gezogene Person Masern und Röteln hatte?
f) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig gezogene Person, die bereits an Masern erkrankte, nun an Windpocken erkrankt?
g) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig gezogene Person, die keine Masern und keine Röteln hatte, an Windpocken erkrankt?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE04
:::
\smallskip\ 





### Aufgabe [-@sec-E05] Schwangerschaftstest {#sec-E05}
::: {.callout-note appearance="simple" icon=false}

Ein Schwangerschaftstest, der von vielen Frauen angewendet wurde, erzielte folgende Ergebnisse.

| Schwanger | Test |  Häufigkeit |
|:---:|:---:|---:|
| Nein | - |  3876|
|Nein| + | 47|
|Ja| - | 12|
|Ja| + |  131|

a) Erstellen Sie ein Datenframe mit den Variablen `Schwanger`, `Testergebnis` und `Häufigkeit`.
b) Erstellen Sie den Wahrscheinlichkeitsraum.
c) Berechnen Sie die Prävalenz der Schwangerschaften.
d) Wie groß ist die Wahrscheinlichkeit, ein positives Testergebnis zu ziehen?
e) Bestimmen Sie die Sensitivität des Tests
f) Bestimmen Sie die Spezifität des Tests
g) Bestimmen Sie den positiv prädiktiven Wert des Tests
h) Bestimmen Sie den negativ prädiktiven Wert des Tests
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE05
:::
\smallskip\ 



### Aufgabe [-@sec-E06] Glückspielwahrscheinlichkeiten {#sec-E06}
::: {.callout-note appearance="simple" icon=false}
Erstelle den Ereignisraum des Zufallsexperiments, das aus dem Werfen einer Münze, dem Werfen eines Würfels und dem Ziehen einer Karte aus einem spanischen Kartenspiel besteht.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE06
:::
\smallskip\ 



### Aufgabe [-@sec-E07] Grippeimpfung {#sec-E07}
::: {.callout-note appearance="simple" icon=false}
Die Wirksamkeit eines Grippeimpfstoffs wurde an 1.000 Probanden erprobt. 

| Impfung | Grippe |  Häufigkeit |
|:---:|:---:|---:|
| Nein | Nein |  418|
|Nein| Ja | 312|
|Ja| Nein | 233|
|Ja| Ja |  37|

a) Erzeugen Sie den Wahrscheinlichkeitsraum 
b) Wie groß ist die Wahrscheinlichkeit, dass eine zufällig ausgewählte Person geimpft ist?
c) Wie hoch ist die Prävalenz der Grippe?
d) Wie groß ist die Wahrscheinlichkeit, dass geimpfte Personen an Grippe erkranken? Ist die Impfung effektiv?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE07
:::
\smallskip\ 



### Aufgabe [-@sec-E08] Ebola {#sec-E08}
::: {.callout-note appearance="simple" icon=false}
Um die Wirksamkeit eines Diagnosetests zur Feststellung von Ebola in einem zentralafrikanischen Land zu ermitteln, wurde der Test an vielen Personen durchgeführt. Das Ergebnis des Tests war positiv bei 147 Personen mit Ebola, aber aber auch bei 28 Personen ohne Ebola. Negativ war das Ergebnis des Tests bei 97465 Personen ohne Ebola, aber auch bei 65 Personen mit Ebola.

a) Erzeugen Sie den Wahrscheinlichkeitsraum des Tests.
b) Berechnen Sie die Prävalenz von Ebola in der Bevölkerung.
c) Wie hoch ist die Wahrscheinlichkeit, ein negatives Testergebnis zu erhalten?
d) Berechnen Sie die Sensitivität und Spezifität des Tests.
e) Kann der Test besser Erkrankte erkennen, oder Gesunde?
f) Wenn eine Person einen positiven Test erhält, wie hoch ist dann die Wahrscheinlichkeit, dass er tatsächlich krank ist?
g) Wenn eine Person einen negativen Test erhält, wie hoch ist dann die Wahrscheinlichkeit, dass er tatsächlich gesund ist?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LE08
:::
\smallskip\ 




## Diskrete Wahrscheinlichkeitsverteilungen {#sec-aufgabeDiskretWahrscheinlich}

### Aufgabe [-@sec-F01] Münzwurf {#sec-F01}
::: {.callout-note appearance="simple" icon=false}

Wir haben 10 mal eine Münze geworfen, wobei das Ergebnis der Binomialverteilung B(10;0.5) folgt. Die Variable `X` misst, wie häufig dabei "`Kopf`" geworfen wurde.  

a) Berechnen Sie die Wahrscheinlichkeitsverteilung von `X`
b) Plotten Sie die Wahrscheinlichkeitsfunktion von `X` 
c) Plotten Sie die Verteilungsfunktion.
d) Berechnen Sie die Wahrscheinlichkeit, 7 mal `Kopf` zu werfen.
e) Berchnen Sie die Wahrscheinlichkeit, weniger als als 4 mal `Kopf` zu werfen.
f) Berchnen Sie die Wahrscheinlichkeit, mehr als als 5 mal `Kopf` zu werfen.
g) Berechnen Sie die Wahrscheinlichkeit, 2 bis 8 mal `Kopf` zu werfen.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF01
:::





### Aufgabe [-@sec-F02] Geburten pro Tag{#sec-F02}
::: {.callout-note appearance="simple" icon=false}
Die Anzahl an täglichen Geburten `X` in unserer Stadt folgt einer Poissonverteilung mit durchschnittlich 6 Geburten am Tag.

a) Plotten Sie die Wahrscheinlichkeitsfunktion von `X`
b) Plotten Sie die Verteilungsfunktion von `X`
c) Wie groß ist die Wahrscheinlicheit, dass an einem zufälligen Tag (nur) 1 Geburt stattfindet? 
d) Wie groß ist die Wahrscheinlicheit, dass an einem zufälligen Tag weniger als 6 Geburten stattfinden? 
e)  Wie groß ist die Wahrscheinlicheit, dass an einem zufälligen Tag  4 oder mehr Geburten stattfinden?
f)  Wie groß ist die Wahrscheinlicheit, dass an einem zufälligen Tag  4 bis 8 Geburten stattfinden?
g)  Wie groß ist die Wahrscheinlicheit, dass in einer Woche zwischen 30 und 40 Geburten stattfinden?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF02
:::
\smallskip\ 





### Aufgabe [-@sec-F03] Gesetz der seltenen Ereignisse {#sec-F03}
::: {.callout-note appearance="simple" icon=false}
Kommen wir nochmal auf das Münzwurfbeispiel aus @sec-F01 zurück.

Das Gesetz der seltenen Ereignisse besagt, dass das Binomial-Verteilungsmodell $B(n,p)$ zum Poisson-Wahrscheinlichkeitsverteilungsmodell $P(np)$ tendiert, wenn $n$ gegen $\infty$ und $p$ gegen $0$ tendiert. Insbesondere ist das Poisson-Modell eine gute Annäherung an das Binomialmodell für $n \geq 30$ und $p \leq 0,1$. 

Zur Überprüfung dieses Gesetz,

a) berechnen Sie die Wahrscheinlichkeitsverteilung des binomialen Modells $B(30, 0.1)$.
b) berechnen Sie die Wahrscheinlichkeitsverteilung des Poissonmodells $P(3)$ und vergleichen Sie es mit dem binomialen Modell $B(30, 0.1)$.
c) berechnen Sie die Wahrscheinlichkeitsverteilung des binomialen Modells $B(100, 0.3)$ und vergleichen Sie es es mit dem Modell $P(3)$. Sind diese Modelle ähnlicher als die vorherigen?
d) Plotten Sie die Wahrscheinlichkeitsfunktionen der vorherigen Modelle. Erhöhen Sie die Anzahl der Wiederholungen und verringern Sie die Erfolgswahrscheinlichkeit im Binomialmodell und beobachten Sie, wie sich die Wahrscheinlichkeiten des Binomialmodells und des Poissonmodells annähern.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF03
:::

### Aufgabe [-@sec-F04] Münzwürfe (II) {#sec-F04}
::: {.callout-note appearance="simple" icon=false}
Wie groß ist die Wahrscheinlichkeit, beim Werfen von 100 Münzen zwischen 40 und 60 Mal `Kopf` zu erhalten (beide Werte eingeschlossen)?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF04
:::



### Aufgabe [-@sec-F05] Behandlungserfolg {#sec-F05}
::: {.callout-note appearance="simple" icon=false}
Die Wahrscheinlichkeit, dass eine Behandlung Erfolg hat, liegt bei 85\%. Wenn wir an 6 Personen die Behandlung durchführen,

a) wie groß ist die Wahrscheinlichkeit, dass die Hälfte der Patienten geheilt wird?
b) wie groß ist die Wahrscheinlichkeit, dass mindestens 4 Patienten geheilt werden?
c) plotten Sie die Wahrscheinlichkeitsfunktion für die Anzahl geheilter Patienten.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF05
:::
\smallskip\ 


### Aufgabe [-@sec-F06] Impfreaktion {#sec-F06}
::: {.callout-note appearance="simple" icon=false}
Die Wahrscheinlichkeit einer starken Impfreaktion beträgt $0,001$. Wenn 2.000 Personen geimpft werden, wie hoch ist die Wahrscheinlichkeit für starke Reaktionen? 
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF06
:::
\smallskip\ 


### Aufgabe [-@sec-F07] Telefonanrufe {#sec-F07}
::: {.callout-note appearance="simple" icon=false}
Die durchschnittliche Anzahl an Telefonanrufen in unserer Telefonzentrale beträgt 120 Anrufe pro Minute.

a) Wie hoch ist die Wahrscheinlichkeit, dass weniger als 4 Anrufe in 2 Sekunden eintreffen?
b) Wie hoch ist die Wahrscheinlichkeit, dass mindestens 3 Anrufe in 3 Sekunden eintreffen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LF07
:::
\smallskip\ 



## Kontinuierliche Wahrscheinlichkeitsverteilungen {#sec-aufgabeKontiWahrscheinlich}

### Aufgabe [-@sec-G01] Bushaltestelle {#sec-G01}
::: {.callout-note appearance="simple" icon=false}

Nehmen wir an, dass ein Bus alle 15 Minuten an einer Haltestelle vorbeifährt und dass eine Person zu jedem Zeitpunkt mit der gleichen Wahrscheinlichkeit eintreffen kann. Dann folgt die Variable, die die Wartezeit auf den Bus misst, einer gleichmäßigen Wahrscheinlichkeitsverteilung $U(0,15)$, da jede Wartezeit zwischen $0$ und $15$ Minuten die gleiche Wahrscheinlichkeit hat.

a) Plotten Sie die Dichtefunktion der Wartezeit.
b) Plotten Sie die Verteilungsfunktion der Wartezeit.
c) Berechnen Sie die Wahrscheinlichkeit, weniger als 5 Minuten auf den Bus zu warten.
d) Berechnen Sie die Wahrscheinlichkeit, länger als 12 Minuten auf den Bus zu warten.
e) Berechnen Sie die Wahrscheinlichkeit, zwischen 5 und 10 Minuten auf den Bus zu warten.
f) Bei welcher Zeit zwischen 0 und 15 Minuten muss die Hälft der Personen kürzer auf den Bus warten als die angegebene Zeit?
g) Bei welcher Zeit zwischen 0 und 15 Minuten müssen 10\% der Personen länger auf den Bus warten als die angegebene Zeit?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG01
:::
\smallskip\ 


### Aufgabe [-@sec-G02] Standardnormalverteilung {#sec-G02}
::: {.callout-note appearance="simple" icon=false}

Eine Variable folgt in ihren Ausprägungen der Standardnormalverteilung ($Z \sim N(0,1)$)

a) Plotten Sie die Dichtefunktion von $Z$.
b) Wie beeinflussen Mittelwert und Standardabweichung die Form der Gausschen Glockenkurve?
c) Plotten Sie die Verteilungsfunktion von $Z$.
d) Berechnen Sie die Wahrscheinlichkeit $P(Z < -1)$.
e) Berechnen Sie die Wahrscheinlichkeit $P(Z > 1)$
f) Berechnen Sie die Wahrscheinlichkeit, dass $Z$ zwischen dem Mittelwert minus der Standardabweichung und dem Mittelwert plus der Standardabweichung liegt, d. h. $P(-1 \leq Z \leq 1)$.
g) Berechnen Sie die Wahrscheinlichkeit, dass $Z$ zwischen dem Mittelwert minus zwei Standardabweichungen und dem Mittelwert plus zwei Standardabweichungen liegt, d. h. $P(-2 \leq Z \leq 2)$.
h) Berechnen Sie die Wahrscheinlichkeit, dass $Z$ zwischen dem Mittelwert minus drei Standardabweichungen und dem Mittelwert plus drei Standardabweichungen liegt, d. h. $P(-3 \leq Z \leq 3)$.
i) Berechnen Sie die Quartile.
j) Bei welchem $Z$-Wert liegen 95\% der Fläche unterhalb des Wertes?
k) Bei welchem $Z$-Wert liegen 2,5\% der Fläche oberhalb des Wertes?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG02
:::
\smallskip\ 


### Aufgabe [-@sec-G03] Chiquadratverteilungen {#sec-G03}
::: {.callout-note appearance="simple" icon=false}

Wenn $X_{1}, \dots, X_{n}$ unabhängige standardnormalverteilte Werte sind, dann folgt die Variable $X = X_{1}^{2} + \dots + X_{n}^{2}$ einer Chiquadratverteilung mit $n$ Freiheitsgraden ($\chi^2(n)$). Nehmen wir nun an, X würde der Chiquadratverteilung mit $6$ Freiheitsgraden folgen ($\chi^2(6)$).

a) Plotten Sie die Dichtefunktion dieser Verteilung
b) Wie groß ist die Wahrscheinlichkeit für $P(X<6)$?
c) Berechnen Sie das fünfte Perzentil der Verteilung.
d) Bei welchem Wert liegen 10\% der Fläche oberhalb des Wertes?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG03
:::
\smallskip\ 



### Aufgabe [-@sec-G04] t-Verteilung {#sec-G04}
::: {.callout-note appearance="simple" icon=false}

Wenn $Y$ einer Chiquadratverteilung mit $n$ Freiheitsgraden folgt ($\chi^2(n)$) und $Z$ der Standardnormalverteilung ($N(0,1)$), dann folgt die Variable $X = \frac{Z}{\sqrt{Y/n}}$ einer Student-t-Verteilung mit 8 Freiheitsgraden ($T(8)$).

a) Plotten Sie die Dichtefunktion von $X$ und vergleichen Sie diese mit der Dichtefunktion der Standardnormalverteilung.
b) Berechnen Sie das 8te Perzentil von $X$.
c) Bei welchem Wert von $X$ liegen 5\% aller Fälle oberhalb dieses Wertes?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG04
:::
\smallskip\ 


### Aufgabe [-@sec-G05] Fishers F-Verteilung {#sec-G05}
::: {.callout-note appearance="simple" icon=false}

Wenn $Y_{1}$ und  $Y_{2}$ zwei unabhängige Variablen aus den Chiquadratverteilungen mit $n$ und $m$ Freiheitsgraden stammen, dann folgt die Variable $X = \frac{Y_{1}/n}{Y_{2}/m}$ einer Fisher-F-Verteilung mit $n$ und $m$ Freiheitsgraden ($F(n,m)$). 
Nehmen wir an, $X$ folge einer Fisher-F-Verteilung mit 10 und 20 Freiheitsgeraden ($F(10,20)$).

a) Plotten Sie die Dichtefunktion von $X$.
b) Berechnen Sie Wahrscheinlichkeit $P(X>1)$.
c) Berechnen Sie den Interquartilsabstand.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG05
:::
\smallskip\ 


### Aufgabe [-@sec-G06] Blutzuckerspiegel {#sec-G06}
::: {.callout-note appearance="simple" icon=false}

Es ist bekannt, dass der Glukosespiegel im Blut von Diabetikern einem Normalverteilungsmodell  mit einem Mittelwert von 106 mg/100 ml und einer Standardabweichung von 8 mg/100 ml folgt.

a) Berechnen Sie die Wahrscheinlichkeit, dass ein zufällig ausgewählter Diabetiker einen Glukosespiegel von weniger als 120 mg/100 ml hat.
b) Wie viel Prozent der Personen haben einen Glukosespiegel zwischen 90 und 120 mg/100 ml?
c) Berechnen und interpretieren Sie das erste Quartil des Glukosespiegels.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG06
:::
\smallskip\ 

### Aufgabe [-@sec-G07] Cholesterinspiegel bei Männern {#sec-G07}
::: {.callout-note appearance="simple" icon=false}

Es ist bekannt, dass der Cholesterinspiegel bei Männern im Alter von 30 Jahren einer Normalverteilung folgt mit Mittelwert 220 mg/dl und einer Standardabweichung von 30 mg/dl. In einer bestimmten Population gibt es 20.000 Männer im Alter von 30 Jahren.

a) Wie viele von ihnen haben einen Cholesterinspiegel zwischen 210 und 240 mg/dl?
b) Wenn ein Cholesterinspiegel von mehr als 250 mg/dl eine Thrombose auslösen kann, wie viele von ihnen sind thrombosegefährdet?
c) Welcher Cholesterinwert wird von mindestens 20% der Männer erreicht?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LG07
:::
\smallskip\ 



## Konfidenzintervalle (eine Stichprobe) {#sec-aufgabeKonfidenzintervalle}

### Aufgabe [-@sec-H01] Wirkstoffkonzentration {#sec-H01}
::: {.callout-note appearance="simple" icon=false}
Die Wirkstoffkonzentration einer Zufallsstichprobe von 10 Arzneimittelbehältern aus einer Charge beträgt (in mg/mm$^{3}$ )


$$
17.6\quad 19.2\quad 21.3\quad 15.1\quad 17.6\quad 18.9\quad 16.2\quad 18.3\quad 19.0\quad 16.4
$$

a) Übertragen Sie die Daten in ein Datenframe mit der Variable `Konzentration`.
b) Berechnen Sie das Konfidenzintervall für die mittlere Konzentration bei einem Konfidenzniveau von 95\% (Signifikanzlevel $\alpha = 0,05$).
c) Berechnen Sie das Konfidenzintervall für die mittlere Konzentration bei einem Konfidenzniveau von 99\% (Signifikanzlevel $\alpha = 0,01$).
d) Wenn wir die Genauigkeit des Intervalls als den Kehrwert seiner Breite definieren, wie ändert sich die Genauigkeit eines Intervalls, wenn wir das Konfidenzniveau erhöhen? Warum?
e) Welche Stichprobengröße wird benötigt, um den mittleren Konzentrationswert mit einem Fehler von $\pm 0.5$mg/mm$^{3}$ und einem Konfidenzniveau von 95\% Sicherheit zu bestimmen?
f) Wenn die Konzentration des Wirkstoffs mindestens 16 mg/mm$^{3}$ betragen muss, um wirksam zu sein, ist dann unsere Medikamentencharge wirksam?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH01
:::
\smallskip\ 


### Aufgabe [-@sec-H02] Milchfett {#sec-H02}
::: {.callout-note appearance="simple" icon=false}
Ein Molkereibetrieb erhält Milch von zwei Bauernhöfen X und Y. Um die Qualität der Milch zu analysieren, wird das Milchfett für zwei Milchproben, eine von jedem Betrieb, gemessen. Die Ergebnisse sind in der nachstehenden Tabelle aufgeführt.

$$
\begin{array}{ll|ll}
\multicolumn{2}{c|}{X} & \multicolumn{2}{c}{Y} \\
\hline
0.34 & 0.34 & 0.28 & 0.29 \\
0.32 & 0.35 & 0.30 & 0.32 \\
0.33 & 0.33 & 0.32 & 0.31 \\
0.32 & 0.32 & 0.29 & 0.29 \\
0.33 & 0.30 & 0.31 & 0.32 \\
0.31 & 0.32 & 0.29 & 0.31 \\
 &  & 0.33 & 0.32 \\
 &  & 0.32 & 0.33 \\
\end{array}
$$


a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Hof1` und `Hof2`.
b) Berechnen Sie das 95\%-Konfidenzintervall für den durchschnittlichen Fettgehalt.
c) Berechnen Sie das 95\%-Konfidenzintervall für den durchschnittlichen Fettgehalt, getrennt nach Höfen.
d) Plotten Sie das 95\%-Konfidenzintervall für den durchschnittlichen Fettgehalt, getrennt nach Höfen.
e) Lässt sich aus den Konfidenzintervallen ein signifikanter Untschied zwischen den Höfen feststellen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH02
:::
\smallskip\ 


### Aufgabe [-@sec-H03] Bibliotheksnutzung {#sec-H03}
::: {.callout-note appearance="simple" icon=false}
In einer von einer Universität durchgeführten Umfrage über die Nutzung der Bibliothek wurde eine Stichprobe von 34 Studierenden gefragt, ob sie mindestens einmal pro Woche in die Bibliothek gehen.

> nein  ja  nein  nein  nein  ja  nein  ja  ja  ja  ja  nein  ja  nein ja  nein  nein nein  ja  ja  ja  nein  nein  ja  nein  nein  ja  ja  nein  nein  ja  nein  ja nein

a) Übertragen Sie die Daten in ein Datenframe mit der Variable `Antwort`.
b) Berechnen Sie das Konfidenzintervall für den Anteil an Studierenden, welche die Bibliothek wöchentlich nutzen mit einem Signifikanzlevel von $\alpha=0,01$.
c) Wie präzise ist das Intervall?
d) Welcher Stichprobenumfang ist erforderlich, um eine Schätzung des Anteils der Studierenden zu erhalten, die die Bibliothek mindestens einmal pro Woche nutzen, mit einem Fehler von $\pm1$\% und einem Konfidenzniveau von 95\%?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH03
:::
\smallskip\ 


### Aufgabe [-@sec-H04] Atemwegsprobleme und Impfung {#sec-H04}
::: {.callout-note appearance="simple" icon=false}
Das Gesundheitsministerium möchte ein Konfidenzintervall für den Anteil der Personen über 65 Jahre mit Atemwegsproblemen berechnen, die geimpft worden sind. In einer Zufallsstichprobe von 200 Personen über 65 mit Atemwegsproblemen wurden 154 geimpft.

a) Berechnen Sie das 95\%-Konfidenzintervall für den Anteil an geimpften Probanden in der Grundgesamtheit.
b) Wenn das Gesundheitsministerium das Ziel verfolgt, dass mindestens 70\% der Menschen über 65 mit Atemwegserkrankungen geimpft sind, können wir dann sagen, dass das Ministerium das Ziel erreicht hat?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH04
:::
\smallskip\ 

### Aufgabe [-@sec-H05] Cholesterin {#sec-H05}
::: {.callout-note appearance="simple" icon=false}

Der Cholesterinspiegel (in mg/dl) in einer Zufallsstichprobe mit 8 Probanden beträgt

> 196 212  188  206  203  210  201  198


a) Berechnen Sie die Konfidenzintervalle für den Mittelwert mit den Signifikanzniveaus $0.1$, $0.05$ und $0.01$. 
B) Kann man schließen, dass der Mittelwert des Cholesterinspiegels der Bevölkerung unter 210 mg/dl liegt?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH05
:::
\smallskip\ 




### Aufgabe [-@sec-H06] Neurologisches Syndrom {#sec-H06}
::: {.callout-note appearance="simple" icon=false}

Zur Behandlung eines neurologischen Syndroms gibt es zwei Therapien, $A$ und $B$. In einer Studie wurde eine Stichprobe von 60 Personen gezogen. Bei 25 von ihnen wurde Therapie $A$ angewandt, bei den anderen 35 Therapie $B$. Insgesmant $18$ der mit $A$ behandelten Personen wurden geheilt, während $21$ der mit $B$ behandelten Personen geheilt wurden. 

a) Berechnen Sie für jede Therapie das 95\% Konfidenzintervall für den Anteil an Personen, die geheilt wurden. 
b) Welches Intervall ist präziser?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH06
:::
\smallskip\ 



### Aufgabe [-@sec-H07] Neugeborene {#sec-H07}
::: {.callout-note appearance="simple" icon=false}

Der Datensatz `neonates` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/neonates.RData>] enthält Informationen über eine Stichprobe von 320 Neugeborenen, die im Laufe eines Jahres nach normaler Schwangerschaftsdauer geboren wurden.


a) Berechnen Sie das 99\% Konfidenzintervall für den Mittelwert des Gewichts der Neugeborenen.
b) Berechnen Sie die Konfidenzintervalle für den APGAR-Score nach 1 Minute und für den APGAR-Score nach 5 Minuten und vergleiche sie beide Intervalle. Gibt es auf Grundlage der Konfidenzintervalle einen signifikanten Unterschied zwischen den Mittelwerten der beiden Scores?
c) Berechnen Sie die Konfidenzintervalle für den Prozentsatz der Neugeborenen mit einem Gewicht von $\leq 2,5$ kg für Raucher- und Nichtrauchermütter und vergleichen Sie die Intervalle.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LH07
:::
\smallskip\ 



## Konfidenzintervalle (zwei Stichproben) {#sec-aufgabeKonfidenzintervalle2}

### Aufgabe [-@sec-I01] Medikamentenwerbung {#sec-I01}
::: {.callout-note appearance="simple" icon=false}
Um festzustellen, ob eine Werbekampagne den Absatz eines Arzneimittels erhöht hat, wurde eine Stichprobe von 8 Apotheken aus einer Stadt gezogen. In jeder Apotheke wurden die monatlichen Verkäufe des Arzneimittels vor und nach der Kampagne in der folgenden Tabelle erfasst.

| Vorher |  147| 163| 121| 205| 132| 190| 176| 147|
|---|---|---|---|---|---|---|---|---|
| Nachher |  150| 171| 132| 208| 141| 184| 182| 145|

a) Erstellen Sie ein Datenframe mit den Variablen `vorher` und `nachher` und übertragen Sie die Daten.
b) Berechnen Sie den Mittelwert der monatlichen Umsätze vor und nach der Kampagne. Sind die Mittelwerte unterschiedlich? Hat die Kampagne den Absatz des Arzneimittels erhöht?
c) Berechnen Sie die Konfidenzintervalle für den durchschnittlichen Unterschied mit $\alpha = 0,05$ und $\alpha = 0,01$.
d) Können wir dieselbe Schlussfolgerung ziehen, wenn wir die Verkäufe nach der Kampagne der beiden letzten Apotheken ändern und $190$ statt $182$ und $165$ statt $145$ angeben? Was passiert mit den Konfidenzintervallen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI01
:::
\smallskip\ 


### Aufgabe [-@sec-I02] Milchfett {#sec-I02}
::: {.callout-note appearance="simple" icon=false}
Ein Molkereibetrieb erhält Milch von zwei Bauernhöfen X und Y. Um die Qualität der Milch zu analysieren, wird das Milchfett für zwei Milchproben, eine von jedem Betrieb, gemessen. Die Ergebnisse sind in der nachstehenden Tabelle aufgeführt.


$$
\begin{array}{ll|ll}
\multicolumn{2}{c|}{X} & \multicolumn{2}{c}{Y} \\
\hline
0.34 & 0.34 & 0.28 & 0.29 \\
0.32 & 0.35 & 0.30 & 0.32 \\
0.33 & 0.33 & 0.32 & 0.31 \\
0.32 & 0.32 & 0.29 & 0.29 \\
0.33 & 0.30 & 0.31 & 0.32 \\
0.31 & 0.32 & 0.29 & 0.31 \\
 &  & 0.33 & 0.32 \\
 &  & 0.32 & 0.33 \\
\end{array}
$$



a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Hof1` und `Hof2`.
b) Berechnen Sie das 95\%-Konfidenzintervall für den durchschnittlichen Fettunterschied in der Milch von `Hof1` und `Hof2`.
c) Kann man daraus schließen, dass der Unterschied zwischen den Milchfettmittelwerten der Betriebe signifikant ist? Welcher Betrieb hat Milch mit mehr Fett? Wie viel mehr Fett hat die Milch von `Hof1` als die Milch von `Hof2`?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI02
:::
\smallskip\ 



### Aufgabe [-@sec-I03] Bibliotheksnutzung nach Geschlecht {#sec-I03}
::: {.callout-note appearance="simple" icon=false}
In einer von einer Universität durchgeführten Umfrage über die Nutzung der Bibliothek wurde eine Stichprobe von 34 Studierenden gefragt, ob sie mindestens einmal pro Woche in die Bibliothek gehen.

|Antwort    | nein | ja | nein | nein | nein | ja | nein | ja | ja | ja | ja | nein |
|---------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Geschlecht | m    | w  |  w   | m    |  m   |  m |  w   |  w |  w |  w | m  | m    |


|Antwort    | nein | ja |  nein|nein  | nein |ja  | ja   | ja | nein |  nein |  ja   |nein | 
|---------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Geschlecht | m    | w  |  m   | m    | w    | m  | w    | w  |  w   | m     | w     | m   |  


|Antwort    | ja |  ja |  nein |  nein |  ja  | nein |  ja | nein | ja |   nein |
|---------|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|Geschlecht | w  |  w  |  m    |   m   |  w | w | w | m | w  |  m   |



a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Antwort` und `Geschlecht`.
b) Berechnen Sie das Konfidenzintervall für den Unterschied zwischen den Anteilen der Frauen und Männern, die die Bibliothek mindestens einmal pro Woche nutzen.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI03
:::
\smallskip\ 


### Aufgabe [-@sec-I04] Prüfungen vormittags und nachmittags {#sec-I04}
::: {.callout-note appearance="simple" icon=false}
In einem Kurs gibt es zwei Gruppen von Studierenden, eine am Vormittag und die andere am Nachmittag. In der Vormittagsgruppe haben 55 von 80 Studierenden bestanden, während in der Nachmittagsgruppe 32 von 90 Studierenden bestanden haben.

a) Gibt es signifikante Unterschiede zwischen den Prozentsätzen der Studierenden, die am Vormittag und am Nachmittag bestanden haben? Kann man daraus schließen, dass der Stundenplan die Ursache für diese Unterschiede ist? 

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI04
:::
\smallskip\ 



### Aufgabe [-@sec-I05] Cholesterin und Sport {#sec-I05}
::: {.callout-note appearance="simple" icon=false}
In einer Studie zur Ermittlung des Zusammenhangs zwischen körperlicher Betätigung und dem Cholesterinspiegel im Blut wurde eine wurde eine Stichprobe von 11 Personen gezogen. Der Cholesterinspiegel der Teilnehmer (in mg/dl) vor und nach der Teilnahme an einem Programm mit körperlichen Übungen ist unten dargestellt.

| vorher |  182 | 232|191| 200| 148| 249| 276| 213| 241| 280| 262|
|---|---|---|---|---|---|---|---|---|---|---|---|
| nachher|  198 | 210| 194| 220| 138| 220| 219| 161| 210| 213| 226|

a) Berechnen Sie das 95\%-Konfidenzintervall für den durchschnittlichen Unterschied der Cholesterinwerte vor und nach den körperlichen Übungen
b) Berechnen Sie das 99\%-Konfidenzintervall für den durchschnittlichen Unterschied der Cholesterinwerte vor und nach den körperlichen Übungen
c) Auf Grundlage der zuvor berechneten Intervalle, welchen Schluss bezüglich des Einflusses von körperlichen Aktivitäten auf den Cholesterinspiegel können Sie ziehen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI05
:::
\smallskip\ 



### Aufgabe [-@sec-I06] Patientenzufriedenheit {#sec-I06}
::: {.callout-note appearance="simple" icon=false}

Insgesamt 500 Patienten aus zwei Krankenhäusern wurden zu ihrer Zufriedenheitbefragt.
In Krankenhaus 1 wurden 200 Patienten befragt, von denen 140 zufrieden waren. In Krankenhaus 2 wurden 300 Patienten befragt, von denen 180 zufrieden waren.

a) Berechnen Sie das 95\%-Konfidenzintervall für den Anteilsunterschied an zufriedenen Patienten in beiden Häusern.
b) Wenn $\alpha = 0,01$ ist, können dann Rückschlüsse gezogen werden, ob der Unterschied der Anteile zufriedener Patienten signifikant ist?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI06
:::
\smallskip\ 



### Aufgabe [-@sec-I07] Neugeborene {#sec-I07}
::: {.callout-note appearance="simple" icon=false}

Der Datensatz `neonates` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/neonates.RData>] enthält Informationen über eine Stichprobe von 320 Neugeborenen, die im Laufe eines Jahres nach normaler Schwangerschaftsdauer geboren wurden.


a) Berechnen Sie das 95\%-Konfidenzintervall für den durchscnnittlichen Unterschied des Geburtsgewichts zwischen Kindern von Raucherinnen und Nichtraucherinnen. Wie groß ist der durchschnittliche Gewichtsunterschied?
b) Berücksichtigen Sie nur die Daten der Mütter, die *während* der Schwangerschaft nicht geraucht haben. Berechnen Sie das 95\%-Konfidenzintervall für den durchscnnittlichen Unterschied des Geburtsgewichts zwischen Kindern von Müttern, die *vor* der Schwangerschaft geraucht haben, und den Nichtraucherinnen.
c) Berechnen Sie das 95\%-Konfidenzintervall für den durchschnittlichen Unterschied von APGAR-1-Werten und APGAR-5-Werten. Wie entwickeln sich Neugeborene in den ersten 5 Minuten nach der Geburt?
d) Wenn Neugeborene mit einem APGAR-1-Wert $\leq3$ in einem kritischen Zustand sind, berechnen Sie das 90\%-Konfidenzintervall für den Unterschied der Anteile von Neugeborenen in kritischem Zustand zwischen Müttern, die *während* der Schwangerschaft geraucht haben und den Nichtraucherinnen.
e) Hat das Alter der Mutter einen signifikanten Einfluss auf den Anteil an Neugeborenen in kritischem Zustand?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LI07
:::
\smallskip\ 


## Signifikanztests {#sec-aufgabeSignifikanztests}

### Aufgabe [-@sec-J01] Wirkstoffkonzentration {#sec-J01}
::: {.callout-note appearance="simple" icon=false}
Die Wirkstoffkonzentration einer Zufallsstichprobe von 10 Arzneimittelbehältern aus einer Charge beträgt (in mg/mm$^{3}$ )


$$
17.6\quad 19.2\quad 21.3\quad 15.1\quad 17.6\quad 18.9\quad 16.2\quad 18.3\quad 19.0\quad 16.4
$$


a) Übertragen Sie die Daten in ein Datenframe mit der Variable `Konzentration`.
b) Testen Sie die zweiseitige Hypothese $H_{0}: \mu = 18$ versus $H_{1}: \mu \neq 18$ mit einem Signifikanzniveau von $\alpha=0,05$.
c) Testen Sie die zweiseitige Hypothese $H_{0}: \mu = 19,5$ versus $H_{1}: \mu \neq 19,5$ mit den Signifikanzniveaus von $\alpha=0,05$ und $0,01$. Wie beeinflusst das Signifikanzniveau das Testergebnis?
d) Testen Sie die zweiseitige Hypothese $H_{0}: \mu = 17$ versus $H_{1}: \mu \neq 17$ mit einem Signifikanzniveau von $\alpha=0,05$. Testen Sie ebenfalls die Hypothesen $H_{0}: \mu = 17$ versus $H_{1}: \mu > 17$ mit $\alpha=0,05$. Was ist der Unterschied zwischen den $p$-Werten des zweiseitigen und des einseitigen Tests?
e) Wenn der Hersteller angibt, die Konzentration des Wirkstoffs erhöht zu haben (im Vergleich zu früheren Chargen, bei denen der Mittelwert der Konzentration 17 mg/mm$^{3}$ war), können wir ihm glauben?
f) Welche Fallzahl würde benötigt, um einen Konzentrationsanstieg von 0,5 mg/mm$^{3}$ zu erkennen (mit $\alpha=0,05$ und einer Power von $1-\beta=0,8$)?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ01
:::
\smallskip\ 


### Aufgabe [-@sec-J02] Bibliotheksnutzung {#sec-J02}
::: {.callout-note appearance="simple" icon=false}
In einer von einer Universität durchgeführten Umfrage über die Nutzung der Bibliothek wurde eine Stichprobe von 34 Studierenden gefragt, ob sie mindestens einmal pro Woche in die Bibliothek gehen.

> nein  ja  nein  nein  nein  ja  nein  ja  ja  ja  ja  nein  ja  nein ja  nein  nein nein  ja  ja  ja  nein  nein  ja  nein  nein  ja  ja  nein  nein  ja  nein  ja nein

a) Übertragen Sie die Daten in ein Datenframe mit der Variable `bib`.
b) Testen Sie die Hypothese, dass der Anteil an Studierenden, die wöchentlich die Bibliothek nutzen, größer als 40% ist.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ02
:::
\smallskip\ 


### Aufgabe [-@sec-J03] Laufen lernen {#sec-J03}
::: {.callout-note appearance="simple" icon=false}

Eine Studie möchte untersuchen, ob Babies aus den unterschiedlichen Populationen $A$ und $B$ zu unterschiedlichen Zeiten anfangen zu laufen. In folgender Tabelle ist das Alter der Babies in Monaten aufgeführt, zu welchem sie mit dem Laufen anfingen.


\begin{center}
\begin{tabular}{lrrrrrrrrrrrr}
\toprule
A & 9.5 & 10.5 & 9.0 & 9.8 & 10.0 & 13.0 & 10.0 & 13.5 & 10.0 & 9.8\\
B & 12.5 & 9.5 & 13.5 & 13.8 & 12.0 & 13.8 & 12.5 & 9.5 & 12.0 & 13.5 & 12.0 & 12.0\\
\bottomrule
\end{tabular}
\end{center}


a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Alter` und `Population`.
b) Testen Sie die Hypothese, dass das durchschnittliche Alter in den Populationen unterschiedlich ist, mit $\alpha = 0,05$.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ03
:::
\smallskip\ 

### Aufgabe [-@sec-J04] Bronchialretention {#sec-J04}
::: {.callout-note appearance="simple" icon=false}
Forschende haben bei Rauchern einen größeren Atemwegswiderstand festgestellt als bei Nichtrauchern. Zur Überprüfung wurde bei 12 Probanden der Prozentsatz der tracheobronchialen Retention gemessen als sie Raucher waren und ein Jahr nach dem Rauchstopp. 


| Rauchen | Nichrauchen |
|:---:|:---:|
|60.6 | 47.5 |
|12.0 | 13.3 |
|56.0 | 33.0 |
|75.2 | 55.2 |
|12.5 | 21.9 |
|29.7 | 27.9 |
|57.2 | 54.3 |
|62.7 | 13.9 |
|28.7 | 8.90 |
|66.0 | 46.1 |
|25.2 | 29.8 |
|40.1 | 36.2 |

a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `vorher` und `nachher`.
b) Testen Sie, ob sich die Bronchialretention nach dem Rauchstopp verringert.
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ04
:::
\smallskip\ 

### Aufgabe [-@sec-J05] Prüfungen vormittags und nachmittags {#sec-J05}
::: {.callout-note appearance="simple" icon=false}
In einem Kurs gibt es zwei Gruppen von Studierenden, eine am Vormittag und die andere am Nachmittag. Unter der Vormittagsgruppe haben 55 von 80 Studierenden bestanden, während in der Nachmittagsgruppe 32 von 90 Studierenden bestanden haben.

a) Gibt es signifikante Unterschiede zwischen den Prozentsätzen der Studiereden, die am Vormittag und am Nachmittag bestanden haben? Kann man daraus schließen, dass der Stundenplan die Ursache für diese Unterschiede ist? 

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ05
:::
\smallskip\ 



### Aufgabe [-@sec-J06] Pulsmessung {#sec-J06}
::: {.callout-note appearance="simple" icon=false}
Der Datensatz `pulse` von rk.Teaching^[<https://github.com/rkward-community/rk.Teaching>, auch verfügbar unter\newline <https://www.produnis.de/R/data/pulse.RData>] enthält Informationen über den Puls einer Stichprobe von Personen nach verschiedenen Übungen:    

- Ruhepuls in Schlägen pro Minute (`pulse1`), 
- Puls nach Bewegung in Schlägen pro Minute (`pulse2`), 
- Art der Bewegung (`type`), 
- Geschlecht (`sex`) und Gewicht (`weight`)

a) Testen Sie, ob der Ruhepuls weniger als 75 Schläge pro Minute beträgt.
b) Welcher Stichprobenumfang ist erforderlich, um einen Anstieg des Ruhepulses um 2 Schläge pro Minute mit einem Signifikanzniveau von 0,05 und einer Power von 0,9 festzustellen? 
c) Testen Sie, ob der Puls nach dem Laufen größer als 85 Schläge pro Minute ist.
d) Eine Person hat eine leichte Tachykardie, wenn der Ruhepuls größer als 90 Schläge pro Minute ist. Prüfen Sie, ob der Prozentsatz der Personen mit leichter Tachykardie größer als 5\% ist.
e) Kann man mit 95\%iger Sicherheit schließen, dass Bewegung den Puls erhöht? Und bei einem Signifikanzniveau von $\alpha =0,01$? 
f) Gibt es einen Unterschied zwischen den durchschnittlichen Pulsschlägen nach dem Gehen und dem Laufen?
g) Gibt es einen Unterschied zwischen den Mittelwerten des Ruhepulses von Männern und Frauen? Und nach dem Laufen? 

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LJ06
:::

\newpage




## Varianzanalysen (ANOVA) {#sec-aufgabeANOVA}

### Aufgabe [-@sec-K01] Aknetherapie {#sec-K01}
::: {.callout-note appearance="simple" icon=false}
In einer Studie wird versucht, die Wirksamkeit von drei Therapieprogrammen $A$, $B$ und $C$ zur Behandlung von von Akne zu bestimmen. Die Teilnehmer der Studie wurden nach dem Zufallsprinzip in drei Gruppen eingeteilt, und in jeder Gruppe wurde eine der Behandlungen durchgeführt. Nach 16 Wochen Behandlung wurde der prozentuale Rückgang der Akneläsionen gemessen.

\begin{center}
\begin{tabular}{rr|rr|rr}
\multicolumn{6}{c}{Reduction in percentage of lesions} \\
\toprule
\multicolumn{2}{c|}{Treatment $A$} & \multicolumn{2}{c|}{Treatment $B$} & \multicolumn{2}{c}{Treatment $C$} \\
48.6 & 50.8 & 68.0 & 71.9 & 67.5 & 61.4 \\
49.4 & 47.1 & 67.0 & 71.5 & 62.5 & 67.4 \\
50.1 & 52.5 & 70.1 & 69.9 & 64.2 & 65.4 \\
49.8 & 49.0 & 64.5 & 68.9 & 62.5 & 63.2 \\
50.6 & 46.7 & 68.0 & 67.8 & 63.9 & 61.2 \\
     &      & 68.3 & 68.9 & 64.8 & 60.5 \\
     &      &      &      & 62.3 &      \\
\bottomrule
\end{tabular}
\end{center}
    
a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Therapie` und `Aknereduktion`.
b) Plotten Sie die Aknereduktion für jede Therapie. Sind Unterschiede erkennbar?
c) Führen Sie eine ANOVA durch. Gibt es signifikante Unterschiede zwischen den Therapien?
d) Berechnen Sie die Konfidenzintervalle für die paarweisen Unterschiede zwischen den drei Behandlungen. Bei welchen Behandlungen gibt es signifikante Unterschiede?
e) Plotten Sie diese Konfidenzintervalle.

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LK01
:::
\smallskip\ 


### Aufgabe [-@sec-K02] Schulranking {#sec-K02}
::: {.callout-note appearance="simple" icon=false}
Um zu prüfen, ob es zwischen den Schulen einer Stadt Unterschiede in den sportlichen Leistungen gibt, wurde eine Zufallsstichprobe von 8 Schülern jeder Schule gezogen. Die erreichten Punkte bei einem Sportwettkampf (von 1 bis 10) der jeweiligen Schüler sind in der folgenden Tabelle dargestellt.

|$A$ | $B$ | $C$ | $D$ | $E$ |
|---|---|---|---|---|
|5.5 | 6.1 | 4.9 | 3.2 | 6.7 |
|5.2 | 7.2 | 5.5 | 3.3 | 5.8 |
|5.9 | 5.5 | 6.1 | 5.5 | 5.4 |
|7.1 | 6.7 | 6.1 | 5.7 | 5.5 |
|6.2 | 7.6 | 6.2 | 6.0 | 4.9 |
|5.9 | 5.9 | 6.4 | 6.1 | 6.2 |
|5.3 | 8.1 | 6.9 | 4.7 | 6.1 |
|6.2 | 8.3 | 4.5 | 5.1 | 7.0 |
    
a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Schule` und `Punkte`.
b) Plotten Sie die durchschnittlich erreichten Punkte pro Schule. Sind Unterschiede erkennbar?
c) Führen Sie eine ANOVA durch. Gibt es signifikante Unterschiede zwischen den Schulen?
d) In welcher Schule sind die sportlichen Leistungen am besten?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LK02
:::
\smallskip\ 


### Aufgabe [-@sec-K03] Puls und Herzkrankheit {#sec-K03}
::: {.callout-note appearance="simple" icon=false}
Die nachstehende Tabelle zeigt den Puls (in Schlägen pro Minute) von vier Patientengruppen: Kontrollen (`A`), Patienten mit Angina pectoris (`B`), Patienten mit Herzrhythmusstörungen (`C`) und Patienten, die sich von einem Herzinfarkt erholt haben (`D`).

|$A$ | $B$ | $C$ | $D$ |
|---|---|---|---|
|83 | 81 | 75 | 61 |
|61 | 65 | 68 | 75 |
|80 | 77 | 80 | 78 |
|63 | 87 | 80 | 80 |
|67 | 95 | 74 | 68 |
|89 | 89 | 78 | 65 |
|71 | 103 | 69 | 68 |
|73 | 89 | 72 | 69 |
|70 | 78 | 76 | 70 |
|66 | 83 | 75 | 79 |
|57 | 91 | 69 | 61 |

a) Gibt es laut den Daten signifikante Unterschiede zwischen den vier Gruppen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LK03
:::
\smallskip\ 



### Aufgabe [-@sec-K04] Kohlenmonoxid {#sec-K04}
::: {.callout-note appearance="simple" icon=false}
Die folgende Tabelle zeigt die Atemfrequenz (Atemzüge pro Minute) bei einer Stichprobe von Laborratten, die drei Konzentrationen von Kohlenmonoxid ausgesetzt waren.

|Low | Medium | High|
|:---:|:---:|:---:|
|36 | 43 | 45 |
|33 | 38 | 39 |
|35 | 41 | 33 |
|39 | 34 | 39 |
|41 | 28 | 33 |
|41 | 44 | 26 |
|44 | 30 | 39 |
|45 | 31 | 29 |

a) Gibt es laut den Daten signifikante Unterschiede zwischen den drei Gruppen?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LK04
:::
\smallskip\ 






## Chiquadratests für Anteilswerte {#sec-aufgabeAChiquadratAnteile}

### Aufgabe [-@sec-AL01] Magengeschwür {#sec-AL01}
::: {.callout-note appearance="simple" icon=false}
Die folgende Tabelle enthält die Blutgruppe einer Stichprobe von 1655 Patienten mit Magengeschwüren und 10000 Patienten ohne Magengeschwüre Patienten.

|   | 0 | A | B | AB |
|:---|:---:|:---:|:---:|:---:|
| Geschwür | 911 | 579 | 124 | 41 |
| kein Geschwür | 4578 | 4219 | 890 | 313 |

a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Geschwuer` und `Blutgruppe`.
b) Führen Sie einen Chiquadrattest auf die Hypothese durch, dass die Geschwüre von der Blutgruppe abhängig sind.
c)  Gibt es in Anbetracht der Ergebnisse des Vergleichs einen Zusammenhang zwischen dem Magengeschwür und der Blutgruppe? Können wir behaupten, dass der Anteil der Ulkuspatienten je nach Blutgruppe unterschiedlich ist?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL01
:::
\smallskip\ 



### Aufgabe [-@sec-AL02] Blutgruppen {#sec-AL02}
::: {.callout-note appearance="simple" icon=false}
@mitchel76 untersuchten die Verteilung der Blutgruppen in einer Stichprobe von 478 Personen aus verschiedenen Regionen im Südwesten Schottlands. Sie erhielten die folgenden Ergebnisse:

$$
\begin{tabular}{|l|l|l|l|l|}
\cline{2-4}
\multicolumn{1}{c|}{} & \multicolumn{1}{c|}{Eskdale} & \multicolumn{1}{c|}{Annandale} & \multicolumn{1}{c|}{Nithsdale} & \multicolumn{1}{c}{} \\
\hline
\multicolumn{1}{|c|}{A} & \multicolumn{1}{c|}{33} & \multicolumn{1}{c|}{54} & \multicolumn{1}{c|}{98} & \multicolumn{1}{c|}{185} \\
\hline
\multicolumn{1}{|c|}{B} & \multicolumn{1}{c|}{6} & \multicolumn{1}{c|}{14} & \multicolumn{1}{c|}{35} & \multicolumn{1}{c|}{55} \\
\hline
\multicolumn{1}{|c|}{O} & \multicolumn{1}{c|}{56} & \multicolumn{1}{c|}{52} & \multicolumn{1}{c|}{115} & \multicolumn{1}{c|}{223} \\
\hline
\multicolumn{1}{|c|}{AB} & \multicolumn{1}{c|}{5} & \multicolumn{1}{c|}{5} & \multicolumn{1}{c|}{5} & \multicolumn{1}{c|}{15} \\
\hline
\multicolumn{1}{c|}{} & \multicolumn{1}{c|}{100} & \multicolumn{1}{c|}{125} & \multicolumn{1}{c|}{253} & \multicolumn{1}{c|}{478} \\
\cline{2-5}
\end{tabular}
$$

a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Region` und `Blutgruppe`.
b) Führen Sie einen Chiquadrattest auf die Hypothese durch, dass die Blutgruppe von der Region abhängig sind.
c)  Gibt es in Anbetracht der Ergebnisse einen Zusammenhang zwischen der Blutgruppe und der Region? Können wir behaupten, dass die Region keinen Einfluss auf die Blutgruppe hat?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL02
:::
\smallskip\ 


### Aufgabe [-@sec-AL03] Rauchen und Geschlecht {#sec-AL03}
::: {.callout-note appearance="simple" icon=false}
In einer Studie wurd versucht festzustellen, ob das Rauchen mit dem Geschlecht zusammenhängt. Es wurden 9 Männer und 17 Frauen befragt. Unter den männlichen Probanden gab es 2 Raucher, während in der weiblichen Stichprobe 6 Raucherinnen waren.


a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `Rauchen` und `Geschlecht`.
b) Führen Sie einen Chi-Quadrat-Test durch, um festzustellen, ob das Rauchen mit dem Geschlecht zusammenhängt.
c) Ist die Verteilung der Raucher bei beiden Geschlechtern gleich?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL03
:::
\smallskip\ 


### Aufgabe [-@sec-AL04] Migräne {#sec-AL04}
::: {.callout-note appearance="simple" icon=false}

Um die Wirksamkeit von zwei Medikamenten gegen Migräne zu vergleichen, wurden 20 Personen, die häufig unter Migräne litten, ausgewählt und die beiden Medikamente zu verschiedenen Zeitpunkten ausprobiert. Die folgende Tabelle zeigt die Anzahl der Personen, die eine gewisse Linderung erfuhren.

| Drug 1 | Yes | Yes | Yes | Yes | Yes | No  | Yes | No  | Yes | Yes |
|---|---|---|---|---|---|---|---|---|---|---|
| Drug 2 | No  | No  | Yes | No  | Yes | Yes | No  | No  | No  | No  |


| Drug 1 | Yes | No  | Yes | No  | Yes | Yes | Yes | No  | Yes | Yes |
|---|---|---|---|---|---|---|---|---|---|---|
| Drug 2 | Yes | No  | Yes | No  | No  | Yes | No  | Yes | No  | No  |



a) Übertragen Sie die Daten in ein Datenframe mit den Variablen `drug1` und `drug2`.
b) Führen Sie einen McNemar-Test durch, um festzustellen, ob die Linderung mit dem Medikament zusammenhängt.
c) Können wir nach dem Ergebnis des Tests behaupten, dass die Linderung der Migräne vom Medikament abhängt? Wenn ja, welches Medikament bewirkt eine signifikant höhere Linderung?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL04
:::
\smallskip\ 


### Aufgabe [-@sec-AL05] Komatös {#sec-AL05}
::: {.callout-note appearance="simple" icon=false}

Eine Studie versucht zu bestimmen, ob Patienten, die bei der Ankunft im Krankenhaus komatös sind, eine schlechtere Prognose (Überleben oder Sterben) haben.


$$
\begin{tabular}{l|l|l|l|}
\cline{2-3}
\multicolumn{1}{c|}{} & \multicolumn{1}{c|}{nicht komatös} & \multicolumn{1}{c|}{komatös} & \multicolumn{1}{c}{} \\
\hline
\multicolumn{1}{|c|}{überleben} & \multicolumn{1}{c|}{484} & \multicolumn{1}{c|}{37} & \multicolumn{1}{c|}{521} \\
\hline
\multicolumn{1}{|c|}{verstorben} & \multicolumn{1}{c|}{118} & \multicolumn{1}{c|}{89} & \multicolumn{1}{c|}{207} \\
\hline
\multicolumn{1}{c|}{} & \multicolumn{1}{c|}{602} & \multicolumn{1}{c|}{126} & \multicolumn{1}{c|}{728} \\
\cline{2-4}
\end{tabular}
$$

a) Ist ein komatöser Zustand bei der Ankunft im Krankenhaus ein Risikofaktor zu versterben?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL05
:::
\smallskip\ 


### Aufgabe [-@sec-AL06] Heilung {#sec-AL06}
::: {.callout-note appearance="simple" icon=false}

Die Heilung einer Krankheit, die durch zwei Behandlungen $A$ und $B$ hervorgerufen wird, wird in drei Kategorien eingeteilt: sehr gut, gut und schlecht. 

Die Behandlung $A$ wird bei 32 Patienten angewandt und $B$ bei 28. Bei Medikament $A$ konnten 10 von insgesamt 22 `sehr guten` Heilungen, 14 von insgesamt 24 `guten` Heilungen  und 8 von insgesamt 14 `schlechten` Heilungen beobachtet werden. Ist die Wirksamkeit der beiden Behandlungen die gleiche?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL06
:::
\smallskip\ 


### Aufgabe [-@sec-AL07] Facherfolg {#sec-AL07}
::: {.callout-note appearance="simple" icon=false}

Um festzustellen, ob Frauen in einem Fach erfolgreicher sind als Männer, wurde eine Stichprobe von 10 Frauen und 10 Männern gezogen. Beide Gruppen wurden von einem Lehrer geprüft, der immer 40\% der Prüflinge durchfallen lässt. Wenn man weiß, dass nur 2 Männer bestanden haben, können wir dann behaupten, dass Frauen in diesem Fach erfolgreicher sind als Männer?
:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL07
:::
\smallskip\ 



### Aufgabe [-@sec-AL08] Statistikdozent {#sec-AL08}
::: {.callout-note appearance="simple" icon=false}

150 Studierende wurden befragt, ob ihnen die Lehrmethoden von zwei Biostatistik-Dozenten (Hans und Erna) gefallen. Die Ergebnisse sind in der nachstehenden Tabelle aufgeführt:

| | like Hans | dislike Hans |
|---|:---:|:---:|
| like Erna | 37 | 48 |
| dislike Erna | 44 | 21 |

Können wir bestätigen, dass es unterschiedliche Meinungen über Hans und Erna gibt?

:::

::: {.callout-tip appearance="simple"}
Für die Lösung siehe @sec-LL08
:::
\smallskip\ 







